### ISSUE TITLE
UNC paths are not supported.  Defaulting to Windows directory.

### ISSUE THREAD

**Issue by rssluca** [AtomLinter/linter-erb#113]
Hi

On Win 10 accessing Mac network folder.

Ver 1.1.0

at ChildProcess.<anonymous> (C:\Users\*****\.atom\packages\linter-erb\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ricardograca** [comment]
No idea what this is about. Care to explain?

**Comment by rssluca** [comment]
Hi  @ricardograca  I have no idea. Atom throws this error every time I open/save an erb file. As I said I am accessing a project folder on a Mac network folder from a Windows 10 workstation.

I had to uninstall the package from now.

**Comment by ricardograca** [comment]
The stack trace isn't super useful since it doesn't show where in linter-erb the error is happening. It could be a problem with sb-exec for all I know. If you could find out that part it would help as I don't use Windows.

Can you see if [this Atom issue](https://github.com/atom/atom/issues/13104) could be related?

**Comment by ricardograca** [comment]
Closing this due to lack of response. If you have any more information to add we can reopen this.
