### ISSUE TITLE
Linter flags <%- notation (as used in devise gem)

### ISSUE THREAD

**Issue by BigMcLargeHuge** [AtomLinter/linter-erb#54]
Hi there,

I've just recently been exposed to an obscure embedded ruby convention that the devise gem seems to be rather fond of.  It embeds ruby code using <%- to apparently block newline creation. 

**For example:**

```
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

```

The linter seems none too fond of this, reporting the following error:

> Unexpected ';'

This seems pretty obscure so it's not exactly a big deal but I thought you might like to know.

**Comment by ricardograca** [comment]
That code isn't correct. It's missing an `end` for the `do` block (or the `if` if you prefer).

**Comment by BigMcLargeHuge** [comment]
> That code isn't correct. It's missing an end for the do block (or the if if you prefer).

@ricardograca My apologies, that was just sloppiness in my transcription.  I've corrected the code above.

**Comment by BigMcLargeHuge** [comment]
>    That code isn't correct. It's missing an end for the do block (or the if if you prefer).

@ricardograca My apologies, that was just sloppiness in my transcription. I've corrected the code above.

**Comment by ricardograca** [comment]
This is strange because this package just passes the code to the `erb` compiler which then passes it through `ruby -c`.

Ok, after further investigation this seems to be related to ERB's trim mode. I'll fix this soon but I'm not sure when an update will be pushed out because we're struggling with [this other issue](https://github.com/AtomLinter/linter-erb/pull/53).

**Comment by ricardograca** [comment]
Oh wait, you can change that in the settings page for this package. If you set it to `-` there won't be any more errors. I'm not exactly sure why it can't be set to that value all the time, so it seems this isn't a bug after all.

**Comment by BigMcLargeHuge** [comment]
Ah, quite correct!  Maybe it shouldn't even be set as default, given that there are other options.  This whole "trim mode" thing is news to me.  Thanks!

**Comment by Arcanemagus** [comment]
Looks like I added that option in the rewrite (#12).... but I have no idea why any more :confused:

Glad it's useful though!

**Comment by ricardograca** [comment]
I have it enabled on my system since this issue was brought up and I didn't notice any side-effects yet. I'm also unsure why we need to specify this thing as an option, but I'll investigate and report back.

**Comment by Arcanemagus** [comment]
If I remember it changes something in the way that `erb` generates the Ruby code, the default closely matching the source so line numbers match up, but other modes fixing some compatibility things (at the cost of not matching).

**Comment by Arcanemagus** [comment]
Ah, here's the documentation: http://ruby-doc.org/stdlib-2.3.1/libdoc/erb/rdoc/ERB.html#method-c-new

**Comment by ricardograca** [comment]
Setting the option to `-` doesn't seem to be affecting the ability to match the error with the correct line. I added a few `<%- -%>` to test this obviously. Maybe we should make `-` the default and change the other options' names to reflect the documentation, i.e. change `0, 1, 2` to `%, <>, >`.

**Comment by Arcanemagus** [comment]
We'd have to convert it back to the number anyway then, the above documentation is for the `ERB()` _class_, the CLI uses the numbers (according to [here](https://docs.oracle.com/cd/E53394_01/html/E54763/erb-1.html), the only documentation I ever found).

**Comment by ricardograca** [comment]
Right, well spotted. I wonder what experienced users find the more intuitive. For me either way is equally confusing since I'm a noob :smile: 

According to those docs I'd say that the other modes won't bring anything useful, but `-` seems like a safe bet since it only affects `<%- -%>`.

I just tested all the trim modes and except for `-` not complaining about `<%-` I don't see any difference.

**Comment by Arcanemagus** [comment]
An `erb` noob is better than I, as I don't use it at all :stuck_out_tongue:.

**Comment by ricardograca** [comment]
@BigMcLargeHuge Any new info you'd like to add here? I think I'm going to go ahead and make `-` the default option.

According to the [docs](http://ruby-doc.org/stdlib-2.3.1/libdoc/erb/rdoc/ERB.html#method-c-new) all it does is:

> omit blank lines ending in -%>

but it seems to fix this issue without causing any bad side effects that I can see. Lines that use this type of brackets, e.g. `<% some_code -%>`, are still linted properly. This option actually seems to be required when using the standard ERB according to this [Stack Overflow answer](http://stackoverflow.com/a/25626629/504930).

Another option would be to use Erubis instead of ERB, which is what Rails does, but that option is too Rails specific, while just changing the default mode to `-` doesn't seem to cause problems to anyone.

**Comment by ricardograca** [comment]
@Arcanemagus I'm running the specs for this locally and I get two errors that a Promise was rejected because `helpers.generateRange` is not a function. The only reference I can find to this is a change you did a few months ago renaming a function to this name. Any ideas on what's going on here?

**Comment by ricardograca** [comment]
@Arcanemagus Never mind. I just realized I need to update my dependencies with `npm`, not `apm`.
